### PR TITLE
Make first attempt at refactoring ggMarginal (should close #38 and #37)

### LINKED ISSUE #38: ggMarginal() not working with ggplot2.2.1.900
I am trying to replicate the example:

```{r}

library("ggplot2")
library("ggExtra")

set.seed(30)
df <- data.frame(x = rnorm(500, 50, 10), y = runif(500, 0, 50))
p <- ggplot(df, aes(x, y)) + geom_point()

ggMarginal(p)

```

Which results the following error:

Error: Don't know how to add o to a plot
In addition: Warning message:
In mean.default(getLimits(pbTop, "y")) :
  argument is not numeric or logical: returning NA

----
Session info:
```{r}
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggExtra_0.6.1      ggplot2_2.2.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9      digest_0.6.12    assertthat_0.1   mime_0.5         grid_3.3.2      
 [6] plyr_1.8.4       R6_2.2.0         xtable_1.8-2     gtable_0.2.0     scales_0.4.1    
[11] lazyeval_0.2.0   miniUI_0.1.1     labeling_0.3     tools_3.3.2      munsell_0.4.3   
[16] shiny_1.0.0.9000 httpuv_1.3.3     colorspace_1.3-2 htmltools_0.3.5  tibble_1.2 
```

### PR DESCRIPTION
**Pull request by crew102**
This PR makes substantial changes to the internal design of `ggMarginal` (mostly towards the beginning of the function). Hopefully it doesn't break anything...

I think there is still more work to be done - there are still several levels of abstraction all mixed about in the main body of `ggMarginal`. Let's start with this and take it from there.

### CODE REVIEW

**Comment by crew102** [comment]
I think we should add support for testing  `ggMarginal` for each version of `ggplot2` that exists, so we don't have to check manually. We could probably just customize the build on travis to do this. Another option would be circleci. Do you have a preference? I don't mind writing the build file, but it should be linked to your account (circleci or travis).

**Comment by daattali** [comment]
Quite the PR! I'll try to take a look on the weekend. Have you tried testing on different ggplot2 versions? 

You're very right that there needs to be some testing system in place. At the time I created the package, I didn't want to add tests because the only possible test I could think of was saving images of different calls and comparing images. It seemed terrible to me. But now after seeing how much time I spend manually testing each version, it was definitely a bad decision to not use tests. So yes, please do go ahead and add tests if you don't mind!

If you do decide to tackle adding tests, maybe it'd be useful to do that first, leave this PR open, generate the tests, and only afterwards come back to this PR to make sure that nothing broke?

Thank you for all your dedication!

**Comment by daattali** [comment]
Also, could you please email me (I wasn't able to find your email or any contact info)

**Comment by daattali** [comment]
Just to make sure we're on the same page: the plan is to add unit testing first, and only once that is working we will come back to tackle this, right? That way we ensure this PR doesn't introduce any regression bugs

**Comment by crew102** [comment]
Yep, that was the plan

**Comment by crew102** [comment]
Hey Dean -

I wanted to see what you thought about me adding myself as a contributor to
ggMarginal in the DESCRIPTION file. I figured it's better to ask in private
than on github.

Chris

**Comment by crew102** [comment]
Sorry, meant to say ggExtra, not marginal

On Thu, Apr 27, 2017 at 4:57 PM, Christopher Baker <chriscrewbaker@gmail.com

**Comment by daattali** [comment]
Of course Chris! I was meaning on doing that after your previous PR was
merged but forgot to. Submit a PR for that :)

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
@crew102 looks like "in private" didn't really work :p But that's ok, your acceptance can be visible to all :)

**Comment by crew102** [comment]
oh whops - didn't realize it was getting published to github...i guess i'll have to assume it was my code and not any public shamming that got me the contrib line :)

**Comment by daattali** [comment]
We'll never know.......

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
Is this PR ready? Is there a unit test for coord_flip()? (to make sure bug #37 doesn't happen in the future)

**Comment by crew102** [comment]
Sorry, was going to add some comments when I got back from home. But yes, a test for coord_flip working should be added - didn't think of that. I'll add, repush, then add some comments for the final pr

**Comment by crew102** [comment]
This PR:

1. Refactors `ggMarginal`
  * Several of the stages/tasks that `ggMaringal` completes to create the final plot are now broken into (more) helper functions 
  * The accession of the `panel_scales` object is now dependent on the `ggplot2` version used (see `getPanelScale` function). This should close #38.
  * We now check if the coordinate system was flipped by the user, and if it was, `ggMarginal` respects that transformation in the final plot (see `needsFlip`). A visual test was added to test this behavior... This should close #37.

2. Adds unit tests to verify our methods/assumptions surrounding ggplot2 internals (together with 1 above this should close #43).

**Comment by daattali** [comment]
This is fantastic! I'll take a look hopefully over the weekend, thank you

File: R/ggMarginal.R [hunk 1]
```diff
@@ -174,73 +120,76 @@ ggMarginal <- function(p, data, x, y, type = c("density", "histogram", "boxplot"
...
-                      extraParams = extraParams)
-    top <- addMainTheme(marginal = top, margin = "x", p = p)
-    top <- top +
-      ggplot2::ylab(p$labels$y) +
-      getScale(margin = "x", type = type, pb = pb)
+  
+  # ... If margins = x or margins = (x and y), then you have to create top plot
+  # Top plot = horizontal margin plot, which corresponds to x marg
+  if (margins != "y") { 
+    rawTop <- genMargePlot(marg = "x", type = type, scatPbuilt = scatPbuilt,
```
Comment (daattali) [inline R/ggMarginal.R]: This will sound petty, but can you change `genMargePlot` to `genMargPlot`? "Marge" is an incorrect spelling, it's not shorthand for anything, either "marg" or "marginal" :)

File: R/ggMarginalHelpers.R [hunk 2]
```diff
@@ -1,78 +1,139 @@
...
-  } else {
-    stop(sprintf("`type` = `%s` is not supported", type), call. = FALSE)
+    prmL$exPrm[['stat']] <- "density"
   }
+
+  prmL$exPrm
+}
+
+getPanelScale <- function(marg, builtP) {
+  panScale <- ifelse(utils::packageVersion("ggplot2") > "2.2.1", "_", "$")
```
Comment (daattali) [inline R/ggMarginalHelpers.R]: I would prefer not to use parse/eval for a trivial task like this. It does save code , but I prefer to resort to these functions only when absolutely necessary. Here it's ok to have two if statements that result in several more lines but result in much clearer code

File: R/ggMarginalHelpers.R [hunk 3]
```diff
@@ -90,121 +151,87 @@ addMainTheme <- function(marginal, margin, p) {
...
-      marginal <- marginal + 
+      rawMarg <- rawMarg + 
         ggplot2::theme(
           axis.title.y = ggplot2::element_blank(),
           axis.text.y = ggplot2::element_blank(),
           plot.margin = grid::unit(c(0, 0, marginLength, 0), marginUnit)
         )
     }
-  }
-  # if this is the old ggplot2 version, things are simpler
```
Comment (daattali) [inline R/ggMarginalHelpers.R]: good call removing old code that never runs

File: R/ggMarginalHelpers.R [hunk 4]
```diff
@@ -90,121 +151,87 @@ addMainTheme <- function(marginal, margin, p) {
...
-    }
+getScale <- function(marg, type, builtP) {
+  
+  scale <- getPanelScale(marg = marg, builtP = builtP)
+  
+  if (type == "boxplot") {
+    scale$limits <- scale$get_limits()
+  }
+  
+  if (needsFlip(marg = marg, type = type)) {
```
Comment (daattali) [inline R/ggMarginalHelpers.R]: In my deleted code, a `gsub()` happens always, but in the new code a `gsub()` only happens when a flip is required. Is this correct?

Comment (crew102) [inline R/ggMarginalHelpers.R]: I believe I matched the logic you had in the original code...In the original version, `gsub` does not always happen. Both versions should have this logic:
```
  # If the marginal plot is: (for the x margin (top) and is a boxplot) or 
  #                          (for the y margin (right) and is not a boxplot), 
  # ... then have to flip
```

**Comment by crew102** [comment]
Hey Dean -

I will make the changes you requested. I have two questions about two chunks of your original code (these chunks are also in the refactor, and I'm wondering if we can get rid of them):

1. What is the purpose of this chunk:
```
    # Add the longest y axis label to the top plot and ensure it's at a y value
    # that is on the plot (this is why I build the top plot, to know the y values)
    pbTop <- ggplot2::ggplot_build(top)
    ylabels <- scatPbuilt$layout$panel_ranges[[1]]$y.labels
    ylabel <- ylabels[which.max(nchar(ylabels))]

    if (type == "boxplot") {
      breaks <- mean(getLimits(marg = "x", builtP = pbTop))
      top <- top + ggplot2::scale_x_continuous(breaks = breaks, labels = ylabel)
    } else {
      breaks <- mean(getLimits(marg = "y", builtP = pbTop))
      top <- top + ggplot2::scale_y_continuous(breaks = breaks, labels = ylabel)
    }
```
and why is it run only when creating the top marginal plot, not the right marginal plot? When I remove this chunk all tests still pass.

2. What is the purpose of this line in `getScale`:
````
  if (type == "boxplot") {
    scale$limits <- scale$get_limits()
  }
````
and why do we apply it only for the boxplot marginal plot? When I remove it all tests still pass (and the issue you raised re: `coord_flip` not working with `type = "boxplot"` seems to be resolved).
Chris

File: R/ggMarginalHelpers.R (hunk 2 above)
Comment (crew102) [inline R/ggMarginalHelpers.R]: Here are the two possible versions:
```
# original
getPanelScale <- function(marg, builtP) {
  panScale <- ifelse(utils::packageVersion("ggplot2") > "2.2.1", "_", "$")
  txtExpr <- paste0("builtP$layout$panel_scales", panScale, marg, "[[1]]")
  panScaleExpr <- parse(text = txtExpr)
  eval(expr = panScaleExpr)
}

# no parse eval
getPanelScale <- function(marg, builtP) {
  above_221 <- utils::packageVersion("ggplot2") > "2.2.1"
  if (above_221) {
    if (marg == "x") {
      builtP$layout$panel_scales_x[[1]]
    } else {
      builtP$layout$panel_scales_y[[1]]
    }
  } else {
    if (marg == "x") {
      builtP$layout$panel_scales$x[[1]]
    } else {
      builtP$layout$panel_scales$y[[1]]
    }
  }
}
```
In my opinion the original version makes the logic clearer. It's not a big issue for me though, so just let me know which version we should go with.

File: R/ggMarginalHelpers.R (hunk 4 above)
Comment (daattali) [inline R/ggMarginalHelpers.R]: You're right, it doesn't always happen.

But in the original code, for boxplots the substitution is x->y and and for others it's y->x. In the new code, it's always x->y.

If it makes sense and works, then ok, I just wanted to make sure it was meant to be like that!

File: R/ggMarginalHelpers.R (hunk 2 above)
Comment (daattali) [inline R/ggMarginalHelpers.R]: The first version is definitely more concise, but I still prefer to avoid the parse+eval combo in this case

Comment (crew102) [inline R/ggMarginalHelpers.R]: OK, no problem

File: R/ggMarginalHelpers.R (hunk 4 above)
Comment (crew102) [inline R/ggMarginalHelpers.R]: I think if we actually cared about the data in y then it would matter, but since we don't, it doesn't matter. We only even need y when its a boxplot, and even then, as long as it's non-null then it doesn't matter what the values are (I think?).

**Comment by daattali** [comment]
1. I don't remember the *exact* plot code that required this logic, this is why I wish I knew about testing in R when I made this! Essentially what was happening was that sometimes (I don't remember when) there would be a long y label - longer than all the other labels - and because of it the original plot would be pushed to the right, and somehow that affected the alignment of the main plot with the top plot. But I really cannot remember what plots cause this. I'm ok with removing this for now so that there is no unknown mystery code, and if this issue ever comes up we can revisit. It's a good evidence of why tests really need to cover all bases :)

2. Again, I have no good answer for you, I'm certain that the limits are added for a good reason, but I cannot remember why. Tracking down when that code was added: https://github.com/daattali/ggExtra/commit/0743b214611896c1a943f461a368b3f113b37961 which references this issue: https://github.com/daattali/ggExtra/issues/18 but I don't think these lines were added for that issue. We can remove this as well.

Anything that was in the original code and was removed (because I didn't make it clear why it was needed!) please document in the NEWS so that we keep track of what was removed.

Thanks for being so thorough - I know it's never fun to have to navigate someone else's code and try to understand what went through his head!

File: R/ggMarginalHelpers.R (hunk 4 above)
Comment (daattali) [inline R/ggMarginalHelpers.R]: remove and make note in NEWS :)

**Comment by crew102** [comment]
OK, I'll remove those and document in NEWS. If it breaks someone's code then we can add back what is needed and add new test cases as well.

**Comment by crew102** [comment]
Last question - Why add the axis labels to the marginal plots when we don't want them there (and they won't show up anyway. due to theme object saying so). For example, on line 183 in ggMarginal.R:
```
top <- top +
      ggplot2::ylab(p$labels$y)
```

**Comment by crew102** [comment]
Nevermind, I think this comment says why:
```
  # - Use the same axis titles as the main plot, to ensure the same space is taken
```

**Comment by daattali** [comment]
I think that's along the reasoning as why I have that code in question 1 above. But I cannot reproduce :)

**Comment by crew102** [comment]
OK, that's what I figured. I'll push changes sometime later today.

**Comment by crew102** [comment]
One thing to note here, running `devtools::check` will throw the following NOTE:
```
margPlotNoGeom: no visible binding for global variable ‘var’
Undefined global functions or variables:
  var
```
I assume we will have to put a comment about this in cran-comments.md when it comes time to resubmit.

**Comment by crew102** [comment]
Hey Dean, don't merge this yet - I think I lost some of my commits along the way.

**Comment by crew102** [comment]
Sorry about that - I was working on two different machines with the same email address and somehow lost some commits along the way. The tip of this branch should contain them all now, though.

File: NEWS.md [hunk 5]
```diff
@@ -1,3 +1,11 @@
+# ggExtra 0.6.1.9000
+
+#### Refactoring of `ggMarginal`:
+- Several of the stages/tasks that `ggMaringal` completes to create the final plot are now broken into (more) helper functions
```
Comment (daattali) [inline NEWS.md]: `ggMaringal` typo

File: NEWS.md [hunk 6]
```diff
@@ -1,3 +1,11 @@
...
+- The accession of the `panel_scales` object is now dependent on the `ggplot2` version used (see `getPanelScale` function)
+- Removed code that added y labels to marginal plot to deal with long y labels as well as spacing issues
```
Comment (daattali) [inline NEWS.md]: Can you add a reference to the actual code so it's easy to find in the future https://github.com/daattali/ggExtra/blob/6c4923c2ad2e700226cdcdc9666de513d6ae3a41/R/ggMarginal.R#L186-L201

File: NEWS.md [hunk 7]
```diff
@@ -1,3 +1,11 @@
...
+- Removed code that set the marginal plot limits when the marginal plot was a boxplot
```
Comment (daattali) [inline NEWS.md]: Reference: https://github.com/daattali/ggExtra/blob/6c4923c2ad2e700226cdcdc9666de513d6ae3a41/R/ggMarginalHelpers.R#L177

**Comment by daattali** [comment]
I do see there are some merge commits today - those really are dangerous and annoying. I always freak out when I accidentally do a merge and then can't properly see what changes were done, it's so unintuitive.... I hope you brought back all the code!

I'll merge tomorrow or the next day

Thanks for also breaking up the work into separate commits, it helps when reviewing

**Comment by daattali** [comment]
I just noticed you mentioned the R CMD NOTE about the binding of var, and I see where it is in the code. I think using `ggplot2::aes_string()` could be used to avoid that, no? CRAN submission is going to be difficult with this NOTE if it seems like there is a way around it!

**Comment by crew102** [comment]
I think this should do it!

**Comment by daattali** [comment]
merging into non-master branch
